import Head from "next/head";

import { AiOutlineMenu, AiOutlineHome, AiOutlineGithub, AiOutlineUser } from "react-icons/ai";
import { IoMdClose } from "react-icons/io";
import { RiFolder2Line } from "react-icons/ri";
import { useEffect, useState } from "react";
import SidebarLink from "./SidebarLink";
import { useRouter } from "next/router";

export default function Layout({ children, title }) {
    const [sidebar, setSidebar] = useState(true);

    const router = useRouter();
    const { pathname } = router;

    useEffect(() => {
        if (typeof window !== "undefined" && window.innerWidth <= 640)
            setSidebar(false);
    }, []);

    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <title>{title ? `${title} | Blog` : "Blog"}</title>
            </Head>

            <nav className="navbar sticky top-0 backdrop-blur w-full h-14 text-gray-300 border-gray-700 border-b">
                <div className="container mx-auto max-w-3xl px-4 h-full flex justify-center items-center">
                    <div className={`flex justify-center items-center h-12 w-8 cursor-pointer ${sidebar && "hidden"}`} onClick={() => setSidebar(!sidebar)}>
                        <AiOutlineMenu size={32} />
                    </div>
                    <div className="flex-1"></div>
                    <h1 className={`font-extrabold text-2xl ${sidebar ? "hidden" : ""}`}>MyName</h1>
                </div>
            </nav>
            <div className={`sidebar ${sidebar ? "" : "sm:-ml-64 msm:hidden"} transition-[margin-left] duration-200 fixed top-0 left-0 w-full sm:w-64 bg-primary h-screen text-gray-300 px-4 flex flex-col`}>
                <div className="flex items-center justify-between h-14 w-full mx-1">
                    <h1 className="font-extrabold text-2xl">MyName</h1>
                    <div className={`flex justify-center items-center h-10 w-10 rounded-full hover:opacity-80 hover:bg-gray-800 cursor-pointer ${sidebar || "hidden"} float-right`} onClick={() => setSidebar(!sidebar)}>
                        <IoMdClose size={30} />
                    </div>
                </div>
                <div className="relative flex-1">
                    <SidebarLink href="/" icon={<AiOutlineHome size={24} />} text="Home" pathname={pathname} />
                    <SidebarLink href="/about" icon={<AiOutlineUser size={24} />} text="About" pathname={pathname} />
                    <SidebarLink href="/projects" icon={<RiFolder2Line size={24} />} text="Projects" pathname={pathname} />
                    <div className="bottom-4 w-full absolute ">
                        <a href="https://www.github.com/epsilonr" className="my-2 flex rounded-md hover:bg-gray-900 transition-colors p-2">
                            <AiOutlineGithub size={26} />
                            <p className="font-semibold ml-2">Github</p>
                        </a>
                        <p className="text-sm ml-2">Made with &#10084; by Epsilonr</p>
                    </div>
                </div>
            </div>

            <main className="text-gray-300 container mx-auto p-4 max-w-3xl">{children}</main>
        </>
    )
};